# -*- coding: utf-8 -*-
"""codigos de practica proyecto3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbyIOM7bbORkzFQmGy-ge5nIkWdMyivB
"""

def pagina_principal():
  st.title("Descripcion del proyecto")
  st.write("Este proyecto tiene como objetivo recopilar y analizar información relevante sobre diversos países del mundo, incluyendo datos sobre su población, idiomas, densidad, area, territorio, etc. A través de una plataforma digital interactiva")




  st.sidebar.title("Navegacion")
  st.sidebar.selectbox("Seleccioona una pagina", {"Pagina principal", "Visualizacion de datos", "Graficos interactivos"})